version: '3.8'

services:
  s3-backup-manager:
    build: .
    container_name: s3-backup-manager
    ports:
      - "5000:5000"
    volumes:
      # Монтирование NFS через host (предполагается, что NFS уже настроен на хосте)
      - /mnt/veeam_nfs:/mnt/veeam_nfs:ro
      # Монтирование для сохранения данных конфигурации и расписаний
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - NFS_PATH=/mnt/veeam_nfs
      - S3_ENDPOINT=172.20.129.1
      - S3_BUCKET=petro-replication-cold-storage
      - S3_ACCESS_KEY=AK06PMXAFAAXQSEO087Y
      - S3_SECRET_KEY=UwHPdFUWH5RFZ74NoHkTDCu6y3i3sYNhLFaGIbEB
      - MAX_THREADS=4
      - BACKUP_DAYS=7
      - STORAGE_CLASS=GLACIER
      - ENABLE_TAPE_STORAGE=false
      - UPLOAD_RETRIES=3
      - RETRY_DELAY=5
      - FLASK_SECRET_KEY=your-secret-key-for-flask
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

 
  # nginx:
  #   image: nginx:alpine
  #   container_name: s3-backup-manager-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro  # для SSL сертификатов
  #   depends_on:
  #     - s3-backup-manager
  #   restart: unless-stopped